kiegroup/jenkins-pipeline-shared-libraries

vars/maven.groovy

@baldimir Any idea how to test such a shared library if it works?

[BAQE-975] Pass properties to a maven build

---

vars/treebuild.groovy

BXMSPROD-592
The idea behind this script is to add these lines to every Jenkinsfile from RHBA project
```
stage('Upstream Build') {
steps {
script {
configFileProvider([configFile(fileId: 'be8694cf-6f0f-443f-8b8a-6464849100bf', variable: 'TREE_FILE_PATH')]) {
def filePath = readFile "${env.TREE_FILE_PATH}"
treebuild.upstreamBuild(filePath.readLines(), treebuild.getProject(env.GIT_URL))
}
}
}
}
stage('Downstream Build') {
steps {
script {
configFileProvider([configFile(fileId: 'be8694cf-6f0f-443f-8b8a-6464849100bf', variable: 'TREE_FILE_PATH')]) {
def filePath = readFile "${env.TREE_FILE_PATH}"
treebuild.downstreamBuild(filePath.readLines())
}
}
}
}
```

BXMSPROD-592 treebuild script

---

vars/pmebuild.groovy

BXMSPROD-583
please squash before merging

BXMSPROD-583 pmebuild.groovy script creation

---

vars/treebuild.groovy

BXMSPROD-592 Files.readAllLines replaced by configFileProvider

---

vars/treebuild.groovy

BXMSPROD-592 project folder removed once the build is finished

---

vars/pmebuild.groovy

BXMSPROD-583 getDefaultBranch method adapted to the new requirements

---

vars/pmebuild.groovy

BXMSPROD-713 CHANGE_AUTHOR environment variable checked for branch builds

---

vars/treebuild.groovy

BXMSPROD-710 treebuild groovy script adapted to github plugin execution

---

vars/pmebuild.groovy

BXMSPROD-719 pmebuild.groovy script improved to properly get branches.

---

vars/pmebuild.groovy

BXMSPROD-719 productVersion variable pointing to env.PRODUCT_VERSION

---

vars/treebuild.groovy

BXMSPROD-710 change dir mechanism and getProjectGroupName method

---

vars/mailer.groovy

BXMSPROD-730 BRANCH_NAME check

---

vars/pmebuild.groovy

BXMSPROD-729 file upload mechanism removed from pmebuild.groovy script

---

vars/treebuild.groovy

BXMSPROD-710 skipTests treatment

---

vars/mailer.groovy

missed the superfluous parenthesis

fixed typos

---

vars/maven.groovy
vars/pmebuild.groovy
vars/treebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-773

BXMSPROD-773 maven log in file

---

vars/maven.groovy

https://issues.redhat.com/browse/BXMSPROD-784
It's the only way I found to maven log either to console and to file and make the job fail in case maven fails

BXMSPROD-784: make maven to fail in case of log file

---

vars/maven.groovy
vars/treebuild.groovy

PLEASE don't merge yet - let's discuss this in next BXMS-prod meetg.

BXMSPROD-753: adapted scripts for using PRs and CDBs

---

vars/maven.groovy
vars/treebuild.groovy

This reverts commit e4cd856c923a1239937921baf2600145df306ea4.

Revert "BXMSPROD-753: adapted scripts for using PRs FDBS and CDBs (#23)"

---

vars/githubscm.groovy
vars/treebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-799

BXMSPROD-799 merge source in target repo mechanism

---

vars/pmebuild.groovy
vars/treebuild.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-801
You can see an execution example here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/BXMSPROD-799-droolsjbpm-build-bootstrap.downstream/32/console
```
------------------------------------------
GIT INFORMATION REPORT
------------------------------------------
kiegroup/lienzo-core: 0f917d4 Expose zoom and pan filters (#102)
kiegroup/lienzo-tests: 45c16e1 Fix tests (#84)
kiegroup/droolsjbpm-build-bootstrap: eaad3e2 Update pom.xml
```

BXMSPROD-801 store and print git information methods

---

vars/githubscm.groovy

https://issues.redhat.com/browse/BXMSPROD-799
I tested locally and the behaviour is exactly the same

BXMSPROD-799 --ff-only removed from githubscm.mergeSourceIntoTarget

---

vars/treebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-778

BXMSPROD-778 avoid to checkout project which triggers job again

---

vars/PipelineHelper.groovy

https://issues.redhat.com/browse/BXMSPROD-781

BXMSPROD-781 PipelineHelper.groovy creation

---

vars/githubscm.groovy
vars/treebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-811

BXMSPROD-811 merge method adapted to use ghprbAuthorRepoGitUrl

---

vars/githubscm.groovy

https://issues.jboss.org/browse/BXMSPROD-758

BXMSPROD-758 user/password for merge command

---

vars/githubscm.groovy
vars/treebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-813

BXMSPROD-813 githubscm.mergeSourceIntoTarget overwritten for kogito's requirements

---

vars/PipelineHelper.groovy

https://issues.redhat.com/browse/BXMSPROD-781
You can see 2 examples here:
- Due to exception:  https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/emingora/job/BXMSPROD-781/job/retry-test/57/console
- Due to timeout: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/emingora/job/BXMSPROD-781/job/retry-test/56/console

BXMSPROD-781 apply a more standard approach to PipelineHelper library

---

vars/PipelineHelper.groovy

https://issues.redhat.com/browse/BXMSPROD-814

BXMSPROD-814 package definition added

---

vars/treebuild.groovy

projectGoalsMap[it] << goals is not working in our jenkins instance

projectGoalsMap[it] << goals replaced by a less syntax sugar approach

---

vars/githubscm.groovy

See: https://issues.redhat.com/browse/KOGITO-2282
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

[KOGITO-2282] - Shared libaries: PR creation

---

vars/githubscm.groovy

Added function for creating branch and commit changes.
Push functionality is part of PR #41
SEE: https://issues.redhat.com/browse/KOGITO-2372
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

[KOGITO-2372] - Shared libaries: Git commit and push

---

vars/githubscm.groovy

See: https://issues.redhat.com/browse/KOGITO-2283
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

[KOGITO-2283] - Shared libaries: PR merging

---

vars/githubscm.groovy

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

removed extra catch from createPR method

---

test/vars/CompileSpec.groovy

https://issues.redhat.com/browse/BXMSPROD-818

BXMSPROD-818 compile.groovy

---

test/vars/PullRequestSpec.groovy

https://issues.redhat.com/browse/BXMSPROD-824

BXMSPROD-824 pullrequest.groovy covered by tests

---

pom.xml
test/resources/build-config.yaml
test/vars/PmeBuildSpec.groovy

https://issues.redhat.com/browse/BXMSPROD-823

BXMSPROD-823 pmebuild.groovy covered by tests

---

pom.xml
test/vars/PipelineHelperSpec.groovy

https://issues.redhat.com/browse/BXMSPROD-822

BXMSPROD-822 PipelineHelper.groovy covered

---

pom.xml
test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/BXMSPROD-819

BXMSPROD-819 githubscm.groovy script covered

---

pom.xml
test/vars/PmeBuildSpec.groovy
vars/PipelineHelper.groovy
vars/pmebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-815

BXMSPROD-815 PipelineHelper retryAction implemented

---

test/vars/TreeBuildSpec.groovy

https://issues.redhat.com/browse/BXMSPROD-825

BXMSPROD-825 treebuild.groovy covered by tests

---

test/resources/goals.properties
test/vars/UtilSpec.groovy
vars/util.groovy

getGoals test was wrong, fixed and its method

Compile error fixed

---

test/resources/project-branches-mapping.properties
test/vars/UtilSpec.groovy
vars/util.groovy

https://issues.redhat.com/browse/PLANNER-2043

branch mapping added

---

test/resources/branched-7-repository-list.txt
test/resources/build-config.yaml
test/resources/nightlyMethods.groovy
test/vars/JenkinsfileNightlySpec.groovy
test/vars/PmeBuildSpec.groovy
vars/pmebuild.groovy

https://issues.redhat.com/browse/PLANNER-2044
depends on: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1378

PLANNER-2044 pmebuild buildConfigAdditionalVariables argument added

---

test/resources/nightlyMethods.groovy

Replaced because of this https://github.com/ExpediaGroup/jenkins-spock/issues/79

it removed from nightlyMethods.groovy

---

test/resources/project-branches-mapping.properties
test/vars/UtilSpec.groovy
vars/util.groovy

There was a missing test case. Please merge it.

util.groovy getMapToBranch

---

test/vars/MavenSpec.groovy
vars/maven.groovy

See: https://issues.redhat.com/browse/KOGITO-2284
Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

[KOGITO-2284] - Shared libaries: Set maven version

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

See: https://issues.redhat.com/browse/KOGITO-2623

[KOGITO-2623] - Make sure hub creds from cache are deleted

---

test/vars/MavenSpec.groovy
vars/maven.groovy

https://issues.redhat.com/browse/KOGITO-2708
- Update parent should be strict to the given version
- Added possibility to allow snapshots or not

KOGITO-2708 Improve Maven version methods

---

test/vars/PullRequestSpec.groovy
test/vars/UtilSpec.groovy
vars/pullrequest.groovy
vars/util.groovy

- pullrequest.groovy delete upstream project dirs
- dirPath selection from `buildSonar` method removed

BXMSPROD-864 project folder deleted after building upstream projects

---

test/vars/PmeBuildSpec.groovy
vars/pmebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-877

BXMSPROD-877 getDefaultBranch adapted to multi target branches

---

test/vars/UtilSpec.groovy
vars/compile.groovy
vars/githubscm.groovy
vars/pullrequest.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-878

BXMSPROD-878 getGoals refactored to read properties file from filesystem

---

test/vars/UtilSpec.groovy
vars/util.groovy

https://issues.redhat.com/browse/KOGITO-2648

Added the function getnextsnapshot in util.groovy KOGITO - 2648

---

vars/pmebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-887

BXMSPROD-887 add DA service to PME execution

---

vars/pmebuild.groovy

This reverts 52856dae69190665d79bea38a864dff5515edbfa
https://issues.redhat.com/browse/BXMSPROD-887

Revert "BXMSPROD-887 add DA service to PME execution (#91)"

---

vars/pmebuild.groovy

This reverts commit b70405abc09657ac92161de265874b404dcd9f81.
https://issues.redhat.com/browse/BXMSPROD-887

Revert "BXMSPROD887 add DA service to PME execution (#90)"

---

test/vars/GithubScmSpec.groovy
test/vars/UtilSpec.groovy
vars/githubscm.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-911
Test job result https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/new-PR-optaweb-employee-rostering-master.pullrequests/31
The changes are basically in `githubscm.groovy` and `util.groovy` scripts

BXMSPROD-911 adapted to take forked projects with different name

---

test/vars/GithubScmSpec.groovy
test/vars/UtilSpec.groovy
vars/githubscm.groovy
vars/util.groovy

This reverts commit a1b1c9e3b8bb56d0a45020acbe00b735e30f3a81 due to problems with Kogito builds
Please merge https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1420 after this

Revert "BXMSPROD-911 adapted to take forked projects with different name (#94)

---

test/vars/UtilSpec.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-919

BXMSPROD-919 Generate hash method

---

test/vars/UtilSpec.groovy
vars/githubscm.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-967
tested here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fullDownstream/job/new-FDB-kie-wb-common-master.downstream/126/console

BXMSPROD-967 jenkins job error cross PR taking forked project name

---

test/vars/PullRequestSpec.groovy
vars/pullrequest.groovy

https://issues.redhat.com/browse/BXMSPROD-991

BXMSPROD-991 array index out of bound error for a non existing project in the collection fixed

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/BXMSPROD-1082
tested here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/nightly/job/master/270

BXMSPROD-1082 getForkedProject improved

---

test/vars/MavenCommandSpec.groovy
test/vars/MavenSpec.groovy
vars/MavenCommand.groovy
vars/maven.groovy

Instead of having many methods (that I kept for backward compatibility), I think it is easier to work with a structure so that we don't have thousands of methods still coming.

Setup class for better flex calling MavenCommand

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/BXMSPROD-1090
tested here and working https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/test/215/
we should test  flows still working.
Once we are sure I will fix project test failures

BXMSPROD-1090 resolveRepository modified

---

vars/compile.groovy
vars/pullrequest.groovy
vars/treebuild.groovy

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1544

check project existence on projectCollection

---

test/vars/PullRequestSpec.groovy
vars/githubscm.groovy

related PR: https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/123

MissingPropertyException checking out exception

---

vars/githubscm.groovy

Use -z cmd instead of [] since [] is replacement for test and test evaluates each word separated by space from files_to_add

Evaluate if staging files set is empty

---

test/vars/CloudSpec.groovy
test/vars/UtilSpec.groovy
vars/cloud.groovy
vars/util.groovy

https://issues.redhat.com/browse/KOGITO-4222
Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/134
- https://github.com/kiegroup/kogito-images/pull/327

KOGITO-4222 Added some cloud methods for Quay

---

vars/pmebuild.groovy

https://issues.jboss.org/browse/BXMSPROD-1115

BXMSPROD-1115 .join() exception fixed

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

to check whether there are current git changes

Added githubscm.isThereAnyChanges

---

test/vars/CloudSpec.groovy
test/vars/UtilSpec.groovy
vars/cloud.groovy
vars/util.groovy

https://issues.redhat.com/browse/KOGITO-4222
Make the method a bit more extensible
Follow-up on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/134

KOGITO-4222 Updated cloud methods to accept 2 types of creds

---

test/vars/CloudSpec.groovy
vars/cloud.groovy

https://issues.redhat.com/browse/KOGITO-4446
Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/141
- https://github.com/kiegroup/kogito-runtimes/pull/1076
- https://github.com/kiegroup/kogito-apps/pull/651
- https://github.com/kiegroup/kogito-examples/pull/569

Kogito-4446 Added cleanup cloud method

---

test/vars/MavenSpec.groovy
test/vars/UtilSpec.groovy
vars/maven.groovy
vars/util.groovy

This method will automatically clean container images, maven repo and call `cleanWs`

Setup clean node util

---

vars/util.groovy

new method to simply check the size of the disk (WORKSPACE and /home/jenkins)
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1597
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/145

new method for measuring disk space

---

vars/pmebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-1212
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/144
https://github.com/kiegroup/kogito-pipelines/pull/123

BXMSPROD-1212 Jenkinsfile.prod.nightly UMB message + date suffix format

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/KOGITO-4635
Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/146
- https://github.com/kiegroup/kogito-runtimes/pull/1127
-

KOGITO-4635 Allow to override the tag if exists

---

test/vars/GithubScmSpec.groovy
test/vars/UtilSpec.groovy
vars/githubscm.groovy
vars/util.groovy

https://issues.redhat.com/browse/BXMSPROD-1250
- https://github.com/kiegroup/kogito-pipelines/pull/137
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/148

BXMSPROD-1250 GIT_INFORMATION_HASHES

---

test/vars/MavenSpec.groovy
vars/maven.groovy

https://issues.redhat.com/browse/BXMSPROD-1289
related PRs:
- https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/369
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/150
- https://github.com/kiegroup/kogito-pipelines/pull/150

[BXMSPROD-1289] getLatestArtifactFromRepository

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://github.com/kiegroup/optaplanner/pull/1300
I know what you are probably thinking, why not to add an additional default argument to the already existing `createPR` method... well... I'm not a big fan of default arguments, specially when they are for adding a new functionality. Once the method is created with default arguments it is not really a good idea to overload it... So at the end I decided to create a new method...

create PR with labels

---

test/vars/GithubScmSpec.groovy
test/vars/PmeBuildSpec.groovy
vars/githubscm.groovy
vars/pmebuild.groovy

Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
https://issues.redhat.com/browse/BXMSPROD-1348

BXMSPROD-1348: avoid temporary build contents in project sources

---

vars/pmebuild.groovy

https://issues.redhat.com/browse/BXMSPROD-1354

BXMSPROD-1354 executeBuildScript additionalFlags argument

---

.github/workflows/maven-tests-PR.yml
test/resources/build-config.yaml
test/resources/forked_projects.json
test/resources/forked_projects_page3.json
test/resources/nightlyMethods.groovy
test/resources/project-branches-mapping.properties
test/resources/pull_request_not_empty.json
test/vars/GithubScmSpec.groovy
test/vars/JenkinsfileNightlySpec.groovy
test/vars/MailerSpec.groovy
test/vars/PmeBuildSpec.groovy
test/vars/UtilSpec.groovy
vars/githubscm.groovy

**JIRA**: [BXMSPROD-1265](https://issues.redhat.com/browse/BXMSPROD-1265)
**referenced Pull Requests**:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1704
https://github.com/kiegroup/kie-jenkins-scripts/pull/1040
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/160
https://github.com/kiegroup/kie-docs/pull/3806

BXMSPROD-1265: Conscientious language initiative [master]

---

test/vars/UtilSpec.groovy
vars/util.groovy

Add possibility to retrieve artifact content and job info

---

test/vars/MailerSpec.groovy
test/vars/UtilSpec.groovy
vars/mailer.groovy
vars/util.groovy

I hope this is the last one for this subject :S

Add possibility of extra info in test summary

---

test/vars/UtilSpec.groovy
vars/util.groovy

Base on first feedback of review

Updated additional info place in message + console log retrieval

---

test/vars/UtilSpec.groovy
vars/util.groovy

And review markdown result to be clearer

Allow to handle multiple console log files

---

test/resources/jira-cve-type.json
test/vars/JiraSpec.groovy
test/vars/RhsaErrataSpec.groovy
vars/jira.groovy
vars/rhsaErrata.groovy

Issue: https://issues.redhat.com/browse/BXMSPROD-670

[BXMSPROD-670] generate CVE content for RHSA errata

---

test/vars/UtilSpec.groovy
vars/pullrequest.groovy
vars/util.groovy

and setup GH format as well for markdown
https://issues.redhat.com/browse/BXMSPROD-1579

[BXMSPROD-1579] Send comment for a pull request

---

test/vars/MailerSpec.groovy
test/vars/UtilSpec.groovy
vars/mailer.groovy
vars/util.groovy

https://issues.redhat.com/browse/KOGITO-6599
Job id in subject instead of content.
It can be empty if needed.

KOGITO-6599 Markdown notification

---

vars/pmebuild.groovy

the idea is to be able to define a specific cleanScript per project

pmebuild cleanScript

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

Jira : https://issues.redhat.com/browse/BXMSPROD-1889
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2136
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1374
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/225

[BXMSPROD-1889] new addRemote method to githubscm.groovy

---

test/resources/build-chain-package.json
test/vars/BuildChainSpec.groovy
vars/buildChain.groovy

Reverts kiegroup/jenkins-pipeline-shared-libraries#259

Revert "fix build-chain version to be installed from node"

---

test/vars/UtilSpec.groovy
vars/util.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2011
Additional utility function that allows to execute closure within Kerberos authentication context

[BXMSPROD-2011] Added withKerberos utility method

---

test/vars/UtilSpec.groovy
vars/util.groovy

withKerberos enhancement, in this way we can skip `kinit` if the principal has been already authenticated.

withKerberos skip kinit if already authenticated

---

test/vars/UtilSpec.groovy
vars/util.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2020
Implement retry mechanism to reduce random failures during Kerberos authentication.

[BXMSPROD-2020] withKerberos: added retry mechanism

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

JIRA: [KOGITO-8455](https://issues.redhat.com/browse/KOGITO-8455)
Dep PRs: 
- [kogito-runtimes](https://github.com/kiegroup/kogito-runtimes/pull/3017)
- [kogito-apps](https://github.com/kiegroup/kogito-apps/pull/1740)
- [kogito-examples](https://github.com/kiegroup/kogito-examples/pull/1678)
- [jenkins-pipeline-shared-libraries](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/275)

KOGITO-8455: added Release Notes creation methods

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/KOGITO-9616

KOGITO-9616 Add `githubscm.deleteReleaseAndTag` method

---

test/vars/GithubScmSpec.groovy
vars/githubscm.groovy

https://issues.redhat.com/browse/KOGITO-9692

KOGITO-9692 Add method githubscm.getPreviousTagFromVersion

---

src/org/kie/jenkins/Utils.groovy
src/org/kie/jenkins/shell/AbstractShell.groovy
src/org/kie/jenkins/shell/LocalShell.groovy
src/org/kie/jenkins/shell/SSHShell.groovy
src/org/kie/jenkins/shell/Shell.groovy
src/org/kie/jenkins/shell/installation/AbstractInstallation.groovy
src/org/kie/jenkins/shell/installation/CRCInstallation.groovy
src/org/kie/jenkins/shell/installation/GolangInstallation.groovy
src/org/kie/jenkins/shell/installation/GroovyInstallation.groovy
src/org/kie/jenkins/shell/installation/Installation.groovy
src/org/kie/jenkins/shell/installation/OpenshiftClientInstallation.groovy
test/vars/AbstractShellSpec.groovy
test/vars/LocalShellSpec .groovy
test/vars/SSHShellSpec.groovy

Those shells allow to easily new binaries on Jenkins (golang, groovy ...) and use them directly (PATH is set automatically)
This can be done with a Local Shell or a remote SSH Shell.
Tested all fine on QE pipelines

Setup Local and SSH shells

---

test/vars/BuildChainSpec.groovy
test/vars/UtilSpec.groovy
vars/buildChain.groovy
vars/util.groovy

Following https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=Using+the+ASF+Jenkins+API

Prepare For Apache migration

---

test/vars/PmeBuildSpec.groovy
vars/pmebuild.groovy

Reverts kiegroup/jenkins-pipeline-shared-libraries#180

Revert "BXMSPROD-1231 return varibles by pmebuild script"

---

vars/pullrequest.groovy

Adjusting postComment method to account for env variables coming from either ghprb or Github Branch Source Plugin.

NO-ISSUE: adjust postComment to Branch Source Plugin

---

vars/jira.groovy

Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/331
- https://github.com/kiegroup/kie-ci/pull/1563

jira.groovy: allow to filter CVEs by a component name
