kiegroup/jenkins-pipeline-shared-libraries

vars/maven.groovy
as they cannot refer to a constant defined outside of them.
=> Return settings.xml reference to methods

vars/mailer.groovy
BXMSPROD-730
The `ghprbSourceBranch` env variable comes from the github plugin we use to trigger a job based on a comment phrase. The `BRANCH_NAME` is not present in these cases
=> BXMSPROD-730 mailer script improved to treat also PRs

vars/pmebuild.groovy, vars/treebuild.groovy
https://issues.redhat.com/browse/BXMSPROD-742
I'm trying to minimise the possibilities of having commits between the starting of the build and the project build itself. It's a simple change I have to test but I would like to know your opinion before spending time here.
Basically I add the checkout at the beginning of the process here https://github.com/Ginxo/jenkins-pipeline-shared-libraries/blob/BXMSPROD-742/vars/treebuild.groovy#L26 and here https://github.com/Ginxo/jenkins-pipeline-shared-libraries/blob/2ff2e8adc39ae5452415ef042099e8541db1434a/vars/pmebuild.groovy#L18 then the checkout for every project is done before any build is performed.
=> BXMSPROD-742 checks out projects at the beginning of the process

vars/githubscm.groovy, vars/treebuild.groovy, vars/util.groovy
https://issues.redhat.com/browse/BXMSPROD-802
So, two things to improve here.
* To retrieve also target repo as a possible place to put branches (not only in forked projects)
* Not to filter branches with PRs from BranchDiscoveryTrait trait (strategy 3)
=> BXMSPROD-802 checkoutIfExists mechanism improved

test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
See: https://issues.redhat.com/browse/KOGITO-2285
This PR adds a `tagRepository` function as per the issue. The core of the code is basically the same as [this CloudBees article](https://support.cloudbees.com/hc/en-us/articles/360027646491-Pipeline-Equivalent-to-Git-Publisher).  I originally used SSH for authentication but realized the existing pipelines used HTTPS, so this also uses HTTPS authentication. The structure of the function mimics `mergeSourceIntoTarget` with using the `checkout` and `resolveRepository` functions to checkout the repository and also annotates progress with info/error messages.
```Jenkinsfile
stage('Tag kogito-runtimes') {
steps {
script {
githubscm.tagRepository('kogito-runtimes', 'kiegroup', 'master', 'Example User', 'example@example.com', 'v2.00')
}
}
}
```
=> [KOGITO-2285] Shared libaries: Git tagging

test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
See: https://issues.redhat.com/browse/KOGITO-2724
`tagRepository` and `commitChanges` tests were updated accordingly.
I ran [a build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-2724/14/console) with the updated `commitChanges` and `tagRepository` that don't have Git committer parameters, and the resulting commit/tag have the globally set Git committer info.
Script:
```groovy
githubscm.commitChanges("Date")
sh "git log -1"
githubscm.tagRepository("$BUILD_TAG", "$BUILD_TAG")
sh "git show ${BUILD_TAG}"
```
Result:
```
...
Author: Jenkins CI <jenkins@rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com>
...
Tagger: Jenkins CI <jenkins@rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com>
```
=> KOGITO-2724 Remove Git committer parameters

test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
See: https://issues.redhat.com/browse/BXMSPROD-948
I tested this fix [in a custom build job](https://jenkins-kogito-tools.apps.kogito.automation.rhmw.io/job/Custom/job/kmok/job/operator-pr-check/5/console).
=> BXMSPROD-948 Fix arguments in getForkedProjectName call

test/vars/UtilSpec.groovy, vars/util.groovy
Allows parsing of versions with suffixes likes:
1.0.0.Final
1.0.0.CR1
etc.
There still must be 3 numeric parts - major, minor, micro. The suffix is optional.
=> Allow version suffix in parseVersion

.jenkins/Jenkinsfile, test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
See: https://issues.redhat.com/browse/BXMSPROD-1126
This PR updates `getRepositoryScm()` to try to checkout the repository in the try/catch block and return null if the repository doesn't exist. I tested [checking out a non-existent branch](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/test/62/console) as well as [an existing one](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/test/64/console).
=> [BXMSPROD-1126] Return null in getRepositoryScm when non-existent

vars/githubscm.groovy
While changing versions I need to stage not only pom files but build.gradle, so I pass it for staging, but not every repo has those files.
Previously returned 1 exit code if no files was found anf git add run
Added a check to not add anything and response with a status in case file was not found.
Problem build https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/adupliak/job/quickstarts-release-pipeline/job/optaplanner-deploy/34/console
Related to https://github.com/kiegroup/optaplanner/pull/1084
=> Do not stage if no files was found

test/vars/MavenSpec.groovy, vars/maven.groovy
See: https://issues.redhat.com/browse/KOGITO-1031
This is an accompanying PR to [the one opened in kogito-pipelines](https://github.com/kiegroup/kogito-pipelines/pull/46). 
- adds function to zip local artifacts and push them to Nexus
* copied from [kie-jenkins-scripts](https://github.com/kiegroup/kie-jenkins-scripts/blob/56e91745ac98d4529b4414ecca37f5f3e87dedc3/job-dsls/jobs/dailyBuild_pipeline.groovy#L111-L114)
I was able to [zip](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031-full/job/kogito-runtimes-deploy/79/execution/node/111/log/?consoleFull) and [push](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031-full/job/kogito-runtimes-deploy/79/execution/node/112/log/) the artifacts to the PR test repository …
=> [KOGITO-1031] Upload local artifacts

test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
error on `curl` command `curl -H 'Authorization: token ****' 'https://api.github.com/repos/kiegroup/optaweb-vehicle-routing/pulls?head=dependabot[bot]:dependabot/npm_and_yarn/optaweb-vehicle-routing-frontend/ini-1.3.7&state=open'` due to `dependabot[bot]` username (the brackets) 
```
--globoff Disable URL sequences and ranges using {} and []
```
Additionally the job `https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/ghprb-webhooks/job/optaweb-vehicle-routing` configuration has been changed.
- pipeline -> repositories -> repository URL: from `https://github.com/${ghprbPullAuthorLogin}/kogito-tooling` to `${ghprbAuthorRepoGitUrl}` to avoid problems in case the PR is not from a forked project
=> BXMSPROD-1149 --globoff added to curl command

vars/pmebuild.groovy
The version has to be shortened to avoid `Argument list too long` failures in daily builds and nightlies
https://github.com/kiegroup/kie-jenkins-scripts/pull/928
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/140
=> shortened version

vars/util.groovy
We encounter a lot of "no space left" errors on several OpenStack nodes. 
Looking at these machines you can see that there are almost two different workspaces.
A workspace should be removed once a job finishes.
We have to dive deeper in what exactly happens on these machines, but as fist step it would be good to have the `cleanWs()` as first action before doing other stuff. It seems that when removing  the `.m2/repository` and two jobs are executing on the same machine (should only theoretically be possible, depending on the number of executers) and one tries to remove the .m2 and one load up some stuff) the `.m2/repository` can't be removed and the [method](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/master/vars/util.groovy#L311) is not fully executed , sso the …
=> cleanWs method as first action of post buils actions (always)

pom.xml
Switching as http is no more supported with Maven 3.8.1+
https://maven.apache.org/docs/3.8.1/release-notes.html
=> Corrected Jenkins repository

src/org/kie/jenkins/MavenCommand.groovy
In case we need the Maven command and run it somewhere else or with different config, allow to retrieve the full command string
=> Small modification on MavenCommand class

test/resources/build-chain-action-single.yml, test/resources/build-chain-action.yml, test/resources/build-chain-package.json, test/vars/BuildChainSpec.groovy, test/vars/GithubScmSpec.groovy, vars/buildChain.groovy
tested by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/droolsjbpm-build-bootstrap-main.pr/242/console
```
12:01:31  build-chain version recovered 2.3.23
[Pipeline] sh
12:01:31  + npm install -g @kie/build-chain-action@2.3.23 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
12:01:37  /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/lib/node_modules/@kie/build-chain-action/bin/build-chain-cli.js
12:01:37  npm WARN notsup Unsupported engine for @kie/build-chain-action@2.3.23: wanted: {"node":">= 12.18.0"} (current: …
```
=> get build-chain version from composite action file

test/vars/MailerSpec.groovy, test/vars/UtilSpec.groovy, vars/mailer.groovy, vars/util.groovy
This will get all info from Jenkins to display job result and test reports if failure/unstable, also get console logs (either from a console.log artifact if existing or directly from the console log)
This is formatting for Zulip (aka Markdown)
Examples of messages can be found in https://kie.zulipchat.com/#narrow/stream/236603-kogito-ci/topic/.5Btest.5D.20Test.20display.20failed.20tests
=> Setup Zulip notification with test results

test/vars/UtilSpec.groovy, vars/util.groovy
This has no added value.
In that way we can also override the default `console.log` file created if no id is given.
This will NOT have any impact on current jobs using it.
=> Remove automatic id for util.archiveConsoleLog

test/vars/UtilSpec.groovy, vars/util.groovy
I noticed that kie-ci1 bot started posting comments with details about failed Jenkins jobs on GitHub PRs. There's a small problem. The comment contains the build number prefixed with `#` which unexpectedly turns it into a link to another GitHub PR or issue. That creates unwanted noise.
=> Do not turn build number into a GH issue/PR link

test/resources/jira-cve-type.json, test/vars/RhsaErrataSpec.groovy, vars/rhsaErrata.groovy
**Jira**:
- https://issues.redhat.com/browse/BXMSPROD-1802
Fixes on **rhsaErrata**: 
- Ignore those jiras that do not match the CVE template, i.e., those that do not start with 'CVE-...'
- Added try-catch such that if something went wrong extracting needed information, only that jira will be skipped
=> [BXMSPROD-1802] Ignore jiras not matching CVE template

test/resources/nightly-config.yaml, test/vars/PmeBuildSpec.groovy, vars/pmebuild.groovy
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1981
**Change Description**:
I exposed a new function `parseBuildConfig` that aims to parse a bacon build-config.yaml exporting its parameters, the exported parameters can then be used by build-chain configuration.
The exported parameters are two:
- `PME_BUILD_SCRIPT_<project>` containing the build script for the specific project , example `PME_BUILD_SCRIPT_kiegroup_projectA=mvn clean deploy`
- `PME_ALIGNMENT_PARAMS_<project>` containing the pme alignment parameters as string "-D... -D... -D...", example `PME_ALIGNMENT_PARAMS_kiegroup_projectA=-DversionOverride=x.y.z`
> Note: the project name is generated by replacing `/` and `-` by `_`
**Referenced Pull Requests:**
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/267 …
=> [BXMSPROD-1981] Add method to export bacon build config

test/vars/UtilSpec.groovy, vars/util.groovy
Since a while 'major.minor.x-prod' is a valid branch for which `setup-branch` should work in order to update the branch version, therefore I am extending `calculateTargetReleaseBranch` to make it working also for those branches as well.
=> calculateTargetReleaseBranch: handle -prod branches

test/vars/GithubScmSpec.groovy, vars/githubscm.groovy
@radtriste tested! 
This prevents the message: 
fatal: ambiguous argument '${branch}': unknown revision or path in the working tree 
when doing a `git rev-parse ${branch}`
=> extended isBranchExist

vars/pullrequest.groovy
Branch Source Plugin does only provide CHANGE_FORK variable in case of PRs coming from forks (obvious, right). When the PR is coming from repository itself (same origin), there is no env variable holding the author_name/repo_name information. Need to parse it from CHANGE_URL.
getAuthorAndRepoForPr will be handy also directly called from the Jenkinsfile.
=> NO-ISSUE: parse CHANGE_URL as fallback for PRs from origin

.github/workflows/maven-tests-PR.yml, test/vars/CloudSpec.groovy, vars/cloud.groovy
Docker build can be really verbose duo to Cekit nature and the whole modules we use in our images. This pollutes the pipelines logs, making debug and troubleshooting quite a challenge. Instead, I've added an option to send this output to a log file, so the pipeline node can archive the result in the `post` stage. The file name has the image plus the platform suffix. Pretty easy to write a regex to archive it after the build.
This PR won't change the default behavior, but pipelines have the option to turnoff the image build logs now.
~Do you guys know how do I test this?~ I've figured.
=> NO-ISSUE - Output docker build logs to a file instead of standard output

test/vars/MavenSpec.groovy, vars/maven.groovy
Fixing a warning `[WARNING] The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.`
=> Sonar.login is deprecated use instead Sonar.token
